name: Generate Snake

# Controls when the action will run
on:
  schedule:
    # Every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Generate snake animation files in ./dist/
      - name: Generate snake files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      # 3️⃣ Optional: Show git status
      - name: Show build status
        run: git status

      # 4️⃣ Push generated files to the output branch
      - name: Push new files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
